PROFESIONALES_ORIGEN = {
    "table_name": "origen_profesionales",
    "order": [
        "id_master",
        "id",
        "idOrigen",
        "origen",
        "apellido",
        "nombre",
        "cuit",
        "genero",
        "titulo",
        "email",
        "telefono",
        "seo",
        "slug_apellido",
        "slug_nombre",
        "eliminado",
        "unificado_prof",
        "createdAt",
        "cambio",
    ],
    "types": {
        "eliminado": "bool",
        "unificado_prof": "bool",
        "id_master": "int",
        "createdAt": "datetime",
        "cambio": "datetime",
    },
}

ESPECIALIDADES_ORIGEN = {
    "table_name": "origen_especialidades",
    "order": [
        "id_master",
        "id",
        "idOrigen",
        "origen",
        "nombre",
        "slug_descripcion",
        "eliminado",
        "unificado_esp",
        "createdAt",
        "cambio",
    ],
    "types": {
        "id_master": "int",
        "eliminado": "bool",
        "unificado_esp": "bool",
        "createdAt": "datetime",
        "cambio": "datetime",
    },
}

OBRAS_SOCIALES_ORIGEN = {
    "table_name": "origen_obras_sociales",
    "order": [
        "id_master",
        "id",
        "idOrigen",
        "origen",
        "nombre",
        "descripcion",
        "habilitado",
        "slug_nombre",
        "slug_descripcion",
        "eliminado",
        "unificado_os",
        "createdAt",
        "cambio",
    ],
    "types": {
        "id_master": "int",
        "eliminado": "bool",
        "habilitado": "bool",
        "unificado_os": "bool",
        "createdAt": "datetime",
        "cambio": "datetime",
    },
}
